language: node_js
node_js:
- "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules

#install:
#- npm install -g yarn

script:
- npm run build -- --base-href /event-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
