language: node_js
node_js:
- "10"
dist: trusty
sudo: false

branches:
  only:
  - master
  - gh-pages

cache:
  directories:
  - node_modules

#install:
#- npm install -g yarn

script:
#- yarn build --base-href https://slowpokex.github.io/event-app/
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
