import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ErrorHandler } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

// Will be automatically generated by set-env script
// @ts-ignore
import { environment } from '../environments/environment';

import { MaterialModule } from './material/material.module';
import { AppStoreModule } from './store/app-store.module';
import { AppRoutingModule } from './routing/app-routing.module';
import { AppFirebaseModule } from './firebase/firebase.module';

// Components
import { AppComponent } from './app.component';
import { MainPageComponent } from './components/main-page/main-page.component';
import { LoginPageComponent } from './components/login-page/login-page.component';
import { AdminPageComponent } from './components/admin-page/admin-page.component';
import { CoreModule } from './core/core.module';

import {
  rollbarFactory,
  RollbarErrorHandler,
  RollbarService
} from './rollbar/rollbar.service';

@NgModule({
  declarations: [
    AppComponent,
    MainPageComponent,
    LoginPageComponent,
    AdminPageComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppFirebaseModule,
    AppStoreModule,
    AppRoutingModule,
    MaterialModule,
    CoreModule
  ],
  providers: [
    { provide: ErrorHandler, useClass: RollbarErrorHandler },
    { provide: RollbarService, useFactory: rollbarFactory }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
